/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColorGameIndexRouteImport } from './routes/color-game/index'
import { Route as TicTacToeIndexRouteImport } from './routes/tic-tac-toe/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorGameIndexRoute = ColorGameIndexRouteImport.update({
  id: '/color-game/',
  path: '/color-game/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicTacToeIndexRoute = TicTacToeIndexRouteImport.update({
  id: '/tic-tac-toe/',
  path: '/tic-tac-toe/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color-game/': typeof ColorGameIndexRoute
  '/tic-tac-toe/': typeof TicTacToeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color-game': typeof ColorGameIndexRoute
  '/tic-tac-toe': typeof TicTacToeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color-game/': typeof ColorGameIndexRoute
  '/tic-tac-toe/': typeof TicTacToeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/color-game/' | '/tic-tac-toe/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/color-game' | '/tic-tac-toe'
  id: '__root__' | '/' | '/color-game/' | '/tic-tac-toe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorGameIndexRoute: typeof ColorGameIndexRoute
  TicTacToeIndexRoute: typeof TicTacToeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-game/': {
      id: '/color-game/'
      path: '/color-game'
      fullPath: '/color-game/'
      preLoaderRoute: typeof ColorGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tic-tac-toe/': {
      id: '/tic-tac-toe/'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe/'
      preLoaderRoute: typeof TicTacToeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorGameIndexRoute: ColorGameIndexRoute,
  TicTacToeIndexRoute: TicTacToeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
